spring.application.name=edutrack-backend

# Database - uses env variable on Render, local value as fallback
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/edutrack_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:karthik5566}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port
server.port=${PORT:8080}