spring.application.name=edutrack-backend

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/edutrack_db
spring.datasource.username=root
spring.datasource.password=karthik5566
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port
server.port=8080


